"""initial audit schema

All tables from docs/DATABASE.md, plus database-level safety triggers:
append-only tables reject UPDATE/DELETE; order intents are never deleted,
their identifying columns are immutable, terminal states are final and an
UNKNOWN order can never go back to created/validated/submitted.

Revision ID: 0001
Revises:
Create Date: 2026-09-24 19:57:00.312480
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from adaptive_quant.persistence.models import APPEND_ONLY

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_versions",
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("resolved_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("config_version", name=op.f("pk_config_versions")),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "symbol", "ex_date", "type", "source", name="uq_corporate_actions_action"
        ),
    )
    op.create_table(
        "daily_performance",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("daily_return", sa.Float(), nullable=False),
        sa.Column("drawdown", sa.Float(), nullable=False),
        sa.Column("turnover", sa.Float(), nullable=False),
        sa.Column(
            "benchmark_returns_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_performance")),
        sa.UniqueConstraint("session_date", "environment", name="uq_daily_performance_session"),
    )
    op.create_table(
        "data_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("frequency", sa.String(length=8), nullable=False),
        sa.Column("adjustment", sa.String(length=16), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("parquet_uri", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_snapshots")),
        sa.UniqueConstraint(
            "provider",
            "symbol",
            "frequency",
            "adjustment",
            "content_hash",
            name="uq_data_snapshots_content",
        ),
    )
    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("leverage", sa.Float(), nullable=False),
        sa.Column("underlying", sa.String(length=16), nullable=True),
        sa.Column("tradeable", sa.Boolean(), nullable=False),
        sa.Column("inception_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_instruments")),
    )
    op.create_table(
        "kill_switch_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("engaged", sa.Boolean(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switch_events")),
    )
    op.create_table(
        "notifications_sent",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications_sent")),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=96), nullable=False),
        sa.Column("implementation", sa.String(length=64), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("research_notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
        sa.UniqueConstraint("strategy_id", "version", name="uq_strategy_versions_strategy_version"),
    )
    op.create_index(
        op.f("ix_strategy_versions_strategy_id"), "strategy_versions", ["strategy_id"], unique=False
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=128), nullable=False),
        sa.Column("context_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    op.create_table(
        "data_quality_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("issues_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.id"],
            name=op.f("fk_data_quality_reports_snapshot_id_data_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_reports")),
    )
    op.create_index(
        op.f("ix_data_quality_reports_snapshot_id"),
        "data_quality_reports",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "research_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("trial_id", sa.String(length=32), nullable=True),
        sa.Column("strategy_version_id", sa.BigInteger(), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("data_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("data_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_snapshot_id"],
            ["data_snapshots.id"],
            name=op.f("fk_research_runs_data_snapshot_id_data_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_research_runs_strategy_version_id_strategy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
    )
    op.create_index(op.f("ix_research_runs_run_id"), "research_runs", ["run_id"], unique=False)
    op.create_index(op.f("ix_research_runs_trial_id"), "research_runs", ["trial_id"], unique=False)
    op.create_table(
        "strategy_lifecycle_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("strategy_version_id", sa.BigInteger(), nullable=False),
        sa.Column("from_state", sa.String(length=16), nullable=False),
        sa.Column("to_state", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_strategy_lifecycle_events_strategy_version_id_strategy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_lifecycle_events")),
    )
    op.create_index(
        op.f("ix_strategy_lifecycle_events_strategy_version_id"),
        "strategy_lifecycle_events",
        ["strategy_version_id"],
        unique=False,
    )
    op.create_table(
        "trading_cycles",
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_version"],
            ["config_versions.config_version"],
            name=op.f("fk_trading_cycles_config_version_config_versions"),
        ),
        sa.PrimaryKeyConstraint("cycle_id", name=op.f("pk_trading_cycles")),
    )
    op.create_index(
        op.f("ix_trading_cycles_session_date"), "trading_cycles", ["session_date"], unique=False
    )
    op.create_table(
        "account_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("is_paper", sa.Boolean(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_account_snapshots_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_snapshots")),
    )
    op.create_index(
        op.f("ix_account_snapshots_cycle_id"), "account_snapshots", ["cycle_id"], unique=False
    )
    op.create_table(
        "ensemble_decisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("strategy_weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("combined_score", sa.Float(), nullable=False),
        sa.Column("combined_exposure", sa.Float(), nullable=False),
        sa.Column("regime_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_ensemble_decisions_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ensemble_decisions")),
    )
    op.create_index(
        op.f("ix_ensemble_decisions_cycle_id"), "ensemble_decisions", ["cycle_id"], unique=False
    )
    op.create_table(
        "errors",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_errors_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_errors")),
    )
    op.create_table(
        "indicator_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("values_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_indicator_snapshots_cycle_id_trading_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["data_snapshot_id"],
            ["data_snapshots.id"],
            name=op.f("fk_indicator_snapshots_data_snapshot_id_data_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator_snapshots")),
    )
    op.create_index(
        op.f("ix_indicator_snapshots_cycle_id"), "indicator_snapshots", ["cycle_id"], unique=False
    )
    op.create_table(
        "portfolio_proposals",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_exposure", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_portfolio_proposals_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_proposals")),
    )
    op.create_index(
        op.f("ix_portfolio_proposals_cycle_id"), "portfolio_proposals", ["cycle_id"], unique=False
    )
    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_position_snapshots_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_snapshots")),
    )
    op.create_index(
        op.f("ix_position_snapshots_cycle_id"), "position_snapshots", ["cycle_id"], unique=False
    )
    op.create_table(
        "preflight_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_preflight_reports_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preflight_reports")),
    )
    op.create_index(
        op.f("ix_preflight_reports_cycle_id"), "preflight_reports", ["cycle_id"], unique=False
    )
    op.create_table(
        "reconciliation_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("differences_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_reconciliation_reports_cycle_id_trading_cycles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_reports")),
    )
    op.create_index(
        op.f("ix_reconciliation_reports_cycle_id"),
        "reconciliation_reports",
        ["cycle_id"],
        unique=False,
    )
    op.create_table(
        "strategy_signals",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_version_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("normalized_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("suggested_exposure", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("indicator_values_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_timestamp <= timestamp", name=op.f("ck_strategy_signals_no_lookahead")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_strategy_signals_cycle_id_trading_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_strategy_signals_strategy_version_id_strategy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_signals")),
    )
    op.create_index(
        op.f("ix_strategy_signals_cycle_id"), "strategy_signals", ["cycle_id"], unique=False
    )
    op.create_table(
        "risk_decisions",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.BigInteger(), nullable=False),
        sa.Column("approved_weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("adjustments_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("drawdown_band", sa.String(length=32), nullable=False),
        sa.Column("drawdown", sa.Float(), nullable=False),
        sa.Column("vol_scale", sa.Float(), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=True),
        sa.Column("blocked_risk_increasing", sa.Boolean(), nullable=False),
        sa.Column("flags_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_risk_decisions_cycle_id_trading_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["portfolio_proposals.id"],
            name=op.f("fk_risk_decisions_proposal_id_portfolio_proposals"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_risk_decisions")),
    )
    op.create_index(
        op.f("ix_risk_decisions_cycle_id"), "risk_decisions", ["cycle_id"], unique=False
    )
    op.create_table(
        "order_intents",
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("tif", sa.String(length=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("risk_increasing", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('buy', 'sell')", name=op.f("ck_order_intents_side")),
        sa.CheckConstraint(
            "state IN ('created', 'validated', 'submitted', 'acknowledged', 'partially_filled', 'filled', 'cancelled', 'rejected', 'unknown')",
            name=op.f("ck_order_intents_state"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_intents_positive_qty")),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_order_intents_cycle_id_trading_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["risk_decisions.decision_id"],
            name=op.f("fk_order_intents_decision_id_risk_decisions"),
        ),
        sa.PrimaryKeyConstraint("client_order_id", name=op.f("pk_order_intents")),
        sa.UniqueConstraint("broker_order_id", name=op.f("uq_order_intents_broker_order_id")),
    )
    op.create_index(op.f("ix_order_intents_cycle_id"), "order_intents", ["cycle_id"], unique=False)
    op.create_table(
        "shadow_orders",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("tif", sa.String(length=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("risk_increasing", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["trading_cycles.cycle_id"],
            name=op.f("fk_shadow_orders_cycle_id_trading_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["risk_decisions.decision_id"],
            name=op.f("fk_shadow_orders_decision_id_risk_decisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_orders")),
        sa.UniqueConstraint("client_order_id", name=op.f("uq_shadow_orders_client_order_id")),
    )
    op.create_index(op.f("ix_shadow_orders_cycle_id"), "shadow_orders", ["cycle_id"], unique=False)
    op.create_table(
        "target_portfolios",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cash_weight", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("net_underlying_exposure", sa.Float(), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_version"],
            ["config_versions.config_version"],
            name=op.f("fk_target_portfolios_config_version_config_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["risk_decisions.decision_id"],
            name=op.f("fk_target_portfolios_decision_id_risk_decisions"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_target_portfolios")),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("broker_execution_id", sa.String(length=64), nullable=False),
        sa.Column("qty", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("fee", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("slippage_bps", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_order_id"],
            ["order_intents.client_order_id"],
            name=op.f("fk_executions_client_order_id_order_intents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("broker_execution_id", name=op.f("uq_executions_broker_execution_id")),
    )
    op.create_index(
        op.f("ix_executions_client_order_id"), "executions", ["client_order_id"], unique=False
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("from_state", sa.String(length=20), nullable=True),
        sa.Column("to_state", sa.String(length=20), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("filled_qty", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("avg_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_order_id"],
            ["order_intents.client_order_id"],
            name=op.f("fk_order_events_client_order_id_order_intents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index("ix_order_events_at", "order_events", ["at"], unique=False)
    op.create_index(
        op.f("ix_order_events_client_order_id"), "order_events", ["client_order_id"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION aq_reject_modification() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit table % is append-only (% refused)', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END $$ LANGUAGE plpgsql;
        """
    )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION aq_reject_modification()"
        )
    for table in ("order_intents", "trading_cycles"):
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION aq_reject_modification()"
        )
    op.execute(
        """
        CREATE FUNCTION aq_guard_order_intent() RETURNS trigger AS $$
        BEGIN
            IF (NEW.client_order_id, NEW.cycle_id, NEW.decision_id, NEW.symbol, NEW.side,
                NEW.quantity, NEW.order_type, NEW.tif, NEW.risk_increasing)
               IS DISTINCT FROM
               (OLD.client_order_id, OLD.cycle_id, OLD.decision_id, OLD.symbol, OLD.side,
                OLD.quantity, OLD.order_type, OLD.tif, OLD.risk_increasing) THEN
                RAISE EXCEPTION 'order intent % is immutable except for its state', OLD.client_order_id
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF OLD.state IN ('filled', 'cancelled', 'rejected') AND NEW.state <> OLD.state THEN
                RAISE EXCEPTION 'order % is in terminal state %', OLD.client_order_id, OLD.state
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF OLD.state = 'unknown' AND NEW.state IN ('created', 'validated', 'submitted') THEN
                RAISE EXCEPTION 'order % is UNKNOWN: investigate, never resubmit', OLD.client_order_id
                    USING ERRCODE = 'restrict_violation';
            END IF;
            NEW.updated_at := now();
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER order_intents_guard BEFORE UPDATE ON order_intents "
        "FOR EACH ROW EXECUTE FUNCTION aq_guard_order_intent()"
    )


def downgrade() -> None:
    # tables are dropped below; their triggers go with them
    op.execute("DROP FUNCTION IF EXISTS aq_guard_order_intent() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS aq_reject_modification() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_events_client_order_id"), table_name="order_events")
    op.drop_index("ix_order_events_at", table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_executions_client_order_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_table("target_portfolios")
    op.drop_index(op.f("ix_shadow_orders_cycle_id"), table_name="shadow_orders")
    op.drop_table("shadow_orders")
    op.drop_index(op.f("ix_order_intents_cycle_id"), table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index(op.f("ix_risk_decisions_cycle_id"), table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_strategy_signals_cycle_id"), table_name="strategy_signals")
    op.drop_table("strategy_signals")
    op.drop_index(op.f("ix_reconciliation_reports_cycle_id"), table_name="reconciliation_reports")
    op.drop_table("reconciliation_reports")
    op.drop_index(op.f("ix_preflight_reports_cycle_id"), table_name="preflight_reports")
    op.drop_table("preflight_reports")
    op.drop_index(op.f("ix_position_snapshots_cycle_id"), table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_index(op.f("ix_portfolio_proposals_cycle_id"), table_name="portfolio_proposals")
    op.drop_table("portfolio_proposals")
    op.drop_index(op.f("ix_indicator_snapshots_cycle_id"), table_name="indicator_snapshots")
    op.drop_table("indicator_snapshots")
    op.drop_table("errors")
    op.drop_index(op.f("ix_ensemble_decisions_cycle_id"), table_name="ensemble_decisions")
    op.drop_table("ensemble_decisions")
    op.drop_index(op.f("ix_account_snapshots_cycle_id"), table_name="account_snapshots")
    op.drop_table("account_snapshots")
    op.drop_index(op.f("ix_trading_cycles_session_date"), table_name="trading_cycles")
    op.drop_table("trading_cycles")
    op.drop_index(
        op.f("ix_strategy_lifecycle_events_strategy_version_id"),
        table_name="strategy_lifecycle_events",
    )
    op.drop_table("strategy_lifecycle_events")
    op.drop_index(op.f("ix_research_runs_trial_id"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_run_id"), table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_index(op.f("ix_data_quality_reports_snapshot_id"), table_name="data_quality_reports")
    op.drop_table("data_quality_reports")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_strategy_versions_strategy_id"), table_name="strategy_versions")
    op.drop_table("strategy_versions")
    op.drop_table("notifications_sent")
    op.drop_table("kill_switch_events")
    op.drop_table("instruments")
    op.drop_table("data_snapshots")
    op.drop_table("daily_performance")
    op.drop_table("corporate_actions")
    op.drop_table("config_versions")
    # ### end Alembic commands ###
